FROM python:3.12-slim
WORKDIR /app

# Copy the master requirements file
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy everything into the container
COPY . .

EXPOSE 8501

# Boot up Streamlit by pointing it to the App folder
CMD ["streamlit", "run", "App/app.py", "--server.port=8501", "--server.address=0.0.0.0"]