FROM python:3.12-slim
WORKDIR /app

# Copy the master requirements file
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy everything from your IBM FINAL folder into the container
COPY . .

EXPOSE 8000

# Boot up the API by pointing Uvicorn to the API folder
CMD ["uvicorn", "API.api:app", "--host", "0.0.0.0", "--port", "8000"]